# Generated by Django 2.2.14 on 2020-08-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='author_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_image',
        ),
    ]
